import { makeQuote } from './actions';
export const metadata = { openGraph: { url: '/', images: '/opengraph-image' } };
import { errorMessage } from '@/lib/errors';
import { emailEnabled } from '@/lib/email';
import { headers } from 'next/headers';
import { QuoteFields } from './components/quote-fields';
import { RecentQuotes, ForgetQuote } from './components/recent-quotes';
import { ArrowUpRight, FilePenLine, ShieldCheck, Sparkles } from 'lucide-react';
export default async function Home({searchParams}:{searchParams:Promise<{error?:string;deleted?:string}>}){const sp=await searchParams,error=errorMessage(sp.error);
// Vercel reports the visitor's country; default the India-only sections from it (on locally, when unknown).
const country=(await headers()).get('x-vercel-ip-country');const defaultRegion=!country||country==='IN'?'IN':'OTHER';return <main className="shell"><div className="hero"><div className="eyebrow"><Sparkles size={14}/> FOR FREELANCE WEB BUILDERS</div><h1>Make the scope clear <em>before</em> the work begins.</h1><p>Turn a rough client ask into a fixed-price quote. Share one approval link and keep every version on record.</p><div className="steps"><a href="#quote-builder"><FilePenLine size={18}/> Draft scope</a><a href="#share-link"><ArrowUpRight size={18}/> Share link</a><a href="#track-approval"><ShieldCheck size={18}/> Track approval</a></div></div><div className="panel" id="quote-builder"><div className="panel-head"><div><span className="kicker">01 / QUOTE BUILDER</span><h2>New project quote</h2></div><span className="draft-pill">DRAFT</span></div>{error&&<p role="alert" className="hint">{error}</p>}{sp.deleted&&<p role="status" className="success">The quote and its history were deleted.</p>}{sp.deleted&&/^[a-f0-9]{24}$/.test(sp.deleted)&&<ForgetQuote id={sp.deleted}/>}<form action={makeQuote} className="form"><QuoteFields defaultRegion={defaultRegion} emailOn={emailEnabled()}/><button className="primary" type="submit">Create quote <ArrowUpRight size={18}/></button></form></div><div className="next-steps"><section id="share-link"><h2>Share link</h2><p>Create a quote first. On its private tracker, copy the client link and send it to your client.</p></section><section id="track-approval"><h2>Track approval</h2><p>Keep the private tracker link for yourself. It shows your quote revisions and the client response.</p></section></div><RecentQuotes/><section className="faq" aria-labelledby="faq"><h2 id="faq">Questions</h2><details><summary>Who is ScopeFirm for?</summary><p>Freelance web designers and developers who quote fixed prices and want the client to agree to exact deliverables, exclusions and revision rounds before work starts.</p></details><details><summary>What happens when the client asks for extra work?</summary><p>After the quote is accepted it is locked. You propose each extra as a priced change order; the client accepts or declines it on the same link, and only accepted changes add to the running total.</p></details><details><summary>Is an approval a legal signature?</summary><p>No. It records which revision was accepted, when, and the name typed. It does not verify identity or take payment. See the <a href="/terms">terms</a>.</p></details><details><summary>Do I need an account?</summary><p>No. You get a private editor link for each quote. Save it: it is the only way back in from another device.</p></details><details><summary>Which currencies are supported?</summary><p>INR, USD, EUR and GBP, with no automatic conversion.</p></details><p><a href="/faq">More questions and answers →</a></p></section></main>}
