// Blog posts are plain data so the page, sitemap, RSS-free index and llms.txt stay in sync.
export type Block = { h: string } | { p: string } | { ul: string[] } | { ol: string[] } | { clause: string };
export type Post = { slug: string; title: string; description: string; date: string; minutes: number; body: Block[]; sources?: { label: string; url: string }[] };

export const posts: Post[] = [
  {
    slug: 'web-design-scope-of-work',
    title: 'How to write a web design scope of work your client can’t misread',
    description: 'A practical template for fixed-price web projects: deliverables, exclusions, revision rounds and a timeline, written so both sides read it the same way.',
    date: '2026-09-28',
    minutes: 6,
    body: [
      { p: 'Most scope arguments are not about bad clients. They start with a scope that could be read two ways. “Five-page website” sounds precise until the client asks whether the blog counts as a page, or whether “responsive” includes a separate mobile menu design.' },
      { p: 'A good scope of work removes the second reading. It is short, specific, and says what is not included just as clearly as what is.' },
      { h: '1. Deliverables: count things, name things' },
      { p: 'Write one deliverable per line, and prefer nouns you can count. “5 pages: Home, About, Services, Portfolio, Contact” beats “a 5-page website”. If a page has a special feature, name it: “Contact page with one form (name, email, message) sending to one inbox.”' },
      { ul: ['Pages by name, not just a number', 'Forms and what they do', 'Integrations by product name (e.g. “Mailchimp signup”, not “email integration”)', 'Who provides content: you, the client, or nobody'] },
      { h: '2. Exclusions: the list that saves the project' },
      { p: 'Exclusions feel negative to write, which is why they are usually missing. They are the single most useful part of a scope because they answer the question before it becomes a request.' },
      { ul: ['Copywriting and photography', 'Hosting, domain and paid plugin fees', 'Pages or features beyond the list above', 'Content entry beyond the pages above', 'Ongoing maintenance after launch'] },
      { h: '3. Revision rounds, defined' },
      { p: 'Say how many rounds are included and what a round is. Without the definition, “two revisions” can become twenty emails. We wrote a separate guide with a clause you can copy: see “What counts as a revision round”.' },
      { h: '4. Timeline with dependencies' },
      { p: 'Give a timeline relative to the things you need: “3 weeks from receiving final content and logins.” A date that ignores dependencies becomes your problem when the client sends content late.' },
      { h: '5. Price, currency and what happens next' },
      { p: 'State the fixed price and currency, any advance, and how extra work is handled: “Work outside this scope is quoted separately as a change order before it starts.” That one sentence makes the later conversation routine instead of awkward.' },
      { h: 'Get it approved, exactly as written' },
      { p: 'Send the scope in a form the client explicitly accepts, and keep a dated copy of the version they accepted. If the scope changes before approval, the client should approve the new version, not a memory of an old one. ScopeFirm does this with one link: the client accepts a specific version, and the history keeps every earlier version.' },
    ],
  },
  {
    slug: 'what-counts-as-a-revision-round',
    title: 'What counts as a revision round (with a clause you can copy)',
    description: '“Two rounds of revisions” means nothing until you define a round. Here is a plain definition and a clause for fixed-price web and design projects.',
    date: '2026-09-28',
    minutes: 4,
    body: [
      { p: 'Revision limits fail in one of two ways: nobody defined a round, so every message became one; or the definition was so strict that clients felt cheated. The fix is a definition that is fair to both sides and easy to apply.' },
      { h: 'A working definition' },
      { p: 'A revision round is one consolidated set of feedback on the delivered work, sent in one message or document, followed by one updated version from you. Feedback that arrives in pieces over several days belongs to the same round until you deliver the update.' },
      { h: 'What a revision is not' },
      { ul: ['A new page, feature or deliverable (that is a change order)', 'A change of direction after approval (new brief, new style)', 'Feedback from a new stakeholder who was not involved earlier, if it reopens approved work'] },
      { h: 'Clause you can copy' },
      { clause: 'This quote includes [2] revision rounds. A revision round is one consolidated set of feedback on the delivered work, followed by one updated version. Please gather all comments for a round into one message. New pages, features or a change of direction are not revisions and will be quoted separately as a change order before work starts. Additional revision rounds are [price] each.' },
      { h: 'How to use it without sounding rigid' },
      { p: 'Mention it once at kickoff, then apply it kindly. When a request falls outside a round, say so plainly and offer the price: “Happy to add this. It’s outside the agreed scope, so here’s a change order for it.” Most clients respect a clear line more than a vague one.' },
      { p: 'In ScopeFirm, the number of included rounds sits next to the price on the client’s approval page, and this definition is shown with it, so it is agreed before work starts.' },
    ],
  },
  {
    slug: 'change-orders-for-freelancers',
    title: 'Change orders for freelancers: a five-minute process',
    description: 'How to turn “can you also add…” into a priced, approved piece of work without an awkward call, and why the approval should come before the work.',
    date: '2026-09-28',
    minutes: 5,
    body: [
      { p: 'Scope creep rarely arrives as one big demand. It arrives as small, reasonable-sounding requests, each too small to argue about, which together add days of unpaid work. Squarespace’s 2026 survey of more than 1,000 web designers ranked scope creep as their second-biggest challenge, after finding clients.' },
      { p: 'A change order is simply a small, separate quote for the extra work, approved before you start it. Here is a process that takes about five minutes.' },
      { h: 'The five steps' },
      { ol: [
        'Check the request against the accepted scope. If it is in scope, do it. If it is not, it is a change order.',
        'Write one line describing the extra work and one price. Add days if it moves the deadline.',
        'Send it to the client as a separate item, not buried in an email thread.',
        'Wait for an explicit yes. Silence is not approval.',
        'Collect payment, or at least an agreed payment date, before or alongside the work.',
      ] },
      { h: 'What to say' },
      { clause: 'Happy to add [the request]. It sits outside the scope we agreed, so I’ve sent it as a separate change: [price], [days] extra. Once you approve it I’ll schedule it in.' },
      { h: 'Why approval comes first' },
      { p: 'After the work is done, the client has little reason to pay more for it. Before the work, a clear price is an easy decision, and a “no” is also useful: it tells you not to spend the time.' },
      { h: 'Keep the original scope intact' },
      { p: 'Do not edit the original quote to add extras. Keep it as the accepted baseline and add change orders on top. That way the running total always shows what was agreed at the start and what was added later.' },
      { p: 'In ScopeFirm, once a quote is accepted it locks, and each extra becomes a change order the client accepts or declines on the same link. Accepted ones show a payment button and can be tracked until you mark them paid.' },
    ],
    sources: [{ label: 'Squarespace Circle, State of the Web Design Industry 2026', url: 'https://pros.squarespace.com/web-design-industry-report' }],
  },
  {
    slug: 'getting-paid-by-clients-abroad',
    title: 'Getting an advance from clients abroad: UPI vs payment links',
    description: 'UPI is easiest for Indian clients, but most clients abroad cannot use it. What to offer each kind of client, and what to keep for your records.',
    date: '2026-09-28',
    minutes: 5,
    body: [
      { p: 'Asking for an advance is normal for fixed-price work: it shows the client is committed and covers your first days. How the client pays depends on where they are.' },
      { h: 'Clients in India paying in rupees: UPI' },
      { p: 'For a rupee quote to an Indian client, a UPI link or ID is usually the fastest option: no card fees for the client and money in your account within seconds. Share your own UPI ID, and tell the client the exact amount and what it is for.' },
      { h: 'Clients outside India: a payment link' },
      { p: 'Most clients abroad cannot pay by UPI; it needs an Indian bank account or a UPI app they are unlikely to have. Give them a payment link instead. Payment links from services such as PayPal, Stripe, Razorpay or Wise let the client pay by card or bank transfer in their own currency.' },
      { ul: ['Compare the fees and currency conversion each service charges before choosing one', 'Quote in the client’s currency if that is what they expect, and state that no conversion is included', 'Check how long money takes to reach your bank'] },
      { h: 'Keep records for export income' },
      { p: 'Money from clients abroad is export of services. Keep the invoice, the payment confirmation and whatever proof of inward remittance your bank or payment service provides. What exactly you need depends on your situation, so confirm with your bank and a chartered accountant rather than relying on a blog post.' },
      { h: 'Ask for the advance at the right moment' },
      { p: 'The best moment is right after the client accepts the scope, while the decision is fresh. In ScopeFirm, the advance appears on the client’s page as soon as they accept: a UPI button for rupee quotes from India-based freelancers, and your payment link for everyone else.' },
    ],
  },
  {
    slug: 'upwork-fiverr-or-direct-clients',
    title: 'Upwork, Fiverr or direct clients: when do you need your own scope tool?',
    description: 'Marketplaces already handle scope, extras and payment protection in their orders. Where that stops, and what to use for clients you find yourself.',
    date: '2026-09-28',
    minutes: 5,
    body: [
      { p: 'If all your work comes through a marketplace, you probably do not need a separate scope tool. The platforms already cover most of it, with escrow on top.' },
      { h: 'What the platforms already do' },
      { ul: [
        'Upwork: fixed-price contracts are split into milestones funded in escrow before work starts, and extra work becomes another milestone.',
        'Fiverr: gig packages include a set number of revisions, and sellers can offer paid extras during an active order.',
        'Upwork Direct Contracts: the same escrow and milestones for clients met outside Upwork, for a service fee.',
      ] },
      { p: 'Moving a client you met on a marketplace off the platform is against its rules unless you pay the platform’s conversion fee, so for those clients the platform’s own tools are the right place.' },
      { h: 'Where you need your own process' },
      { p: 'Much freelance work comes from referrals, past clients, LinkedIn and local businesses. Those clients may not want to sign up to a marketplace, and you may not want to pay a platform fee on every project. That is where you need your own way to agree scope, handle extras and collect advances.' },
      { h: 'What that process needs' },
      { ul: ['A written scope the client explicitly accepts, with a dated record', 'A way to price extras before doing them', 'A way to request an advance that suits where the client is', 'Your own record of what has been paid and what is overdue'] },
      { p: 'ScopeFirm is built for exactly that direct-client case: no accounts for your clients, one link to approve, change orders on the same link, and a payments sheet you can download. It does not hold money in escrow, so for large projects with unknown clients, an escrow service can still be the safer choice.' },
    ],
    sources: [
      { label: 'Upwork: How payments for milestones and fixed-price contracts work', url: 'https://support.upwork.com/hc/en-us/articles/211063718-How-payments-for-milestones-and-fixed-price-contracts-work' },
      { label: 'Upwork: Direct Contracts', url: 'https://support.upwork.com/hc/en-us/articles/360025040794-Direct-Contracts-bring-a-client-to-Upwork' },
      { label: 'Upwork: Circumvention policy', url: 'https://support.upwork.com/hc/en-us/articles/360052511133-Circumvention-and-why-it-s-against-the-rules' },
      { label: 'Fiverr: Offering extra services within an active order', url: 'https://help.fiverr.com/hc/en-us/articles/360010791778-Offering-extra-services-within-an-active-order' },
    ],
  },
];

export const postBySlug = (slug: string) => posts.find(p => p.slug === slug);
